version: "1.0"

stages:
  - "clone"
  - "build"
  - deploy
  - "test"
  - post

steps:

  build:
    title: "Building App"
    image: "codefresh/cli"
    stage: "build"
    commands:
      - echo "Building App"

  calculateDate:
    image: ubuntu:latest
    stage: deploy
    commands:
      - |
        START_DATE=`date -u '+%Y-%m-%d %H:%M:%S'`
        END_DATE=`date -u -d '+1 day' '+%Y-%m-%d %H:%M:%S'`
        echo START_DATE=\"$START_DATE\" >> ${{CF_VOLUME_PATH}}/env_vars_to_export
        echo  END_DATE=\"$END_DATE\" >> ${{CF_VOLUME_PATH}}/env_vars_to_export
        
  createCR:
    type: service-now:${{VERSION}}
    title: Create Service Now Change Request
    stage: deploy
    arguments:
      CR_ACTION: createCR
      SN_USER: admin
      SN_PASSWORD: '${{SN_PASSWORD}}'
      SN_INSTANCE: ${{SN_INSTANCE}}
      TOKEN: ${{CF_TOKEN}}
      CR_CONFLICT_POLICY: ignore
      CR_DATA: >-
        {
          "short_description": "Application deployment to Prod", 
          "description": "Change for build ${{CF_BUILD_ID}}\nThis change was created by the Codefresh plugin", 
          "justification": "I do not need a justification\nMy app is awesome", 
          "cmdb_ci":"tomcat",
        "start_date":${{START_DATE}},
        "end_date":${{END_DATE}}
        }

  approval:
    stage: deploy
    description: "Approval to deploy to PROD"
    type: pending-approval
    timeout:
      duration: 2
      finalState: denied    

  modifyCR:
    stage: deploy
    title: "Modify the implementation plan"
    type: service-now:${{VERSION}}
    fail_fast: false
    arguments:
      CR_ACTION: updateCR
      CR_SYSID: ${{CR_SYSID}}
      SN_USER: admin
      SN_PASSWORD: '${{SN_PASSWORD}}'
      SN_INSTANCE: ${{SN_INSTANCE}}
      CR_DATA: '{"implementation_plan":"The implementation has been approved."}' 

  deploy:
    title: "Deploying App"
    image: "codefresh/cli"
    stage: "deploy"
    commands:
      - echo "Deploying App"
      - sleep 5

  test:
    title: "Testing App"
    image: "codefresh/cli"
    stage: "test"
    commands:
      - echo "Testing App"
      - sleep 10

  modifyTestPlan:
    stage: test
    title: "Modify the test plan"
    type: service-now:${{VERSION}}
    fail_fast: false
    arguments:
      CR_ACTION: updateCR
      CR_SYSID: ${{CR_SYSID}}
      SN_USER: admin
      SN_PASSWORD: '${{SN_PASSWORD}}'
      SN_INSTANCE: ${{SN_INSTANCE}}
      CR_DATA: '{"test_plan":"The testing suit has passed."}'
  wait2:
    stage: post
    title: are we ready to close?
    type: pending-approval
    timeout:
      duration: 10
      timeUnit: minutes
      finalState: approved  
      
  closeCR:
    type: service-now:${{VERSION}}
    title: Close Service Now Change Request
    stage: post
    arguments:
      CR_ACTION: closeCR
      CR_SYSID: ${{CR_SYSID}}
      SN_USER: admin
      SN_PASSWORD: '${{SN_PASSWORD}}'
      SN_INSTANCE: ${{SN_INSTANCE}}
      CR_CLOSE_CODE: "successful"
      CR_CLOSE_NOTES: "Closed automatically by Codefresh build ${{CF_BUILD_ID}}"
      CR_DATA: '{"work_notes":"this is a message for the work notes"}'